#!/bin/sh

# set the clock from IOS
#add hostname to /etc/hosts
routerip=`traceroute -m 3 4.4.4.4 | head -3 | tail -1 | awk '{ print $2}'`

/usr/sbin/ntpd -n -q -p $routerip

# set the timezone from configfile
tz=`awk '/tz/{ print $3 }' /data/package_config.ini`

# if not set, then set to UTC
if [ -z $tz ]; then
	export TZ=UTC
else
# set new TZ
	export TZ=$tz
fi

# for backward compat
cd /usr/src/app
/usr/bin/python logrotate.py
